[build]
  # Qaysi papka ichida build qilishni aytamiz
  base = "frontend"
  
  # Build qilish buyrug'i
  command = "npm run build"
  
  # Natija qaysi papkada chiqishini aytamiz
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200